name: Run Unit Tests and Lint Files
"on": push
jobs:
    test_lint_format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                  npm ci
                  npm run build
                  npm run test
                  npm run lint
                  npm run format
